somedayrainbows/ralesengine

Gemfile, Gemfile.lock, app/controllers/api/v1/merchants_controller.rb, app/controllers/api/v1/transactions_controller.rb, app/serializers/invoice_serializer.rb, app/serializers/merchant_serializer.rb, app/serializers/transaction_serializer.rb, lib/tasks/data.rake
Adds serialization
Adds created_at and updated_at to seeds
=> Serialization and seed change

app/controllers/api/v1/invoice_items_controller.rb, app/models/invoice_item.rb, app/serializers/invoice_items_serializer.rb, config/routes.rb, db/migrate/20170502194644_create_invoice_items.rb, db/schema.rb, lib/tasks/data.rake, spec/factories/invoice_items.rb, spec/models/invoice_item_spec.rb, spec/requests/api/v1/invoice_items_request_spec.rb
* Wrote request spec for invoice item and TDD’d:
* Updated routes for index, show for invoice items
* Ran migration to create invoice items table
* Added invoice items CSV to rake file
* Created invoice item controller and model
* Added invoice item serializer
* Created invoice item factory
=> Adds invoice_item record endpoint

Gemfile, Gemfile.lock, app/models/invoice.rb, app/models/item.rb, app/models/merchant.rb, db/migrate/20170503002657_add_merchant_to_invoices.rb, db/migrate/20170503003828_add_merchant_to_items.rb, db/schema.rb, spec/factories/merchants.rb, spec/models/merchant_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/invoices_request_spec.rb, spec/requests/api/v1/items_request_spec.rb
* Set up should-matchers
* Set up item belongs_to merchant
* Set up invoice belongs_to merchant
* Set up merchant has_many items, invoices
* Ran migrations to add merchant_id to items, invoices
=> Add relationship among merchant, invoices, items

app/models/customer.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/transaction.rb, app/serializers/invoice_items_serializer.rb, app/serializers/invoice_serializer.rb, app/serializers/item_serializer.rb, app/serializers/transaction_serializer.rb, db/migrate/20170503151249_add_invoices_to_transactions.rb, db/migrate/20170503152635_add_customer_to_invoices.rb, db/migrate/20170503154036_add_item_to_invoice_items.rb, db/migrate/20170503154358_add_invoices_to_invoice_items.rb, db/schema.rb, spec/models/customer_spec.rb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb, spec/models/transaction_spec.rb, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/invoices_request_spec.rb, spec/requests/api/v1/transactions_request_spec.rb
Added model tests, relationships for all, ran migrations to update table to reflect relationships
* Still need to update routes to reflect relationships
=> Finishes all relationship endpoints

app/models/customer.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/transaction.rb, app/serializers/invoice_items_serializer.rb, app/serializers/invoice_serializer.rb, app/serializers/item_serializer.rb, app/serializers/transaction_serializer.rb, db/migrate/20170503151249_add_invoices_to_transactions.rb, db/migrate/20170503152635_add_customer_to_invoices.rb, db/migrate/20170503154036_add_item_to_invoice_items.rb, db/migrate/20170503154358_add_invoices_to_invoice_items.rb, db/schema.rb, spec/models/customer_spec.rb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb, spec/models/transaction_spec.rb, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/invoices_request_spec.rb, spec/requests/api/v1/transactions_request_spec.rb
Removed cc exp date from serializer because all fields in that column are empty in CSV
=> Remove cc exp date from serializer

lib/tasks/seed.rake, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/invoices_request_spec.rb, spec/requests/api/v1/items_request_spec.rb, spec/requests/api/v1/transactions_request_spec.rb
* Per Casey’s feedback (thank you! 👍 )
* Reran and fixed tests; now passing
=> Adds bangs to create in tests and seeds

lib/tasks/seed.rake
* Added the remaining columns in seed file to enable rake seed to run for all
=> Fixes seed file to reflect relationships

app/serializers/invoice_item_serializer.rb, app/serializers/invoice_items_serializer.rb, app/serializers/item_serializer.rb, db/migrate/20170503192750_update_transaction_cc_column.rb, db/schema.rb
*Change Invoice Item serializer to singular
*Change credit card format in table to string
*Change JSON output of unit price to a string in cents by adding a method in the serializers.
=> Fix problems to pass spec harness tests

app/controllers/api/v1/merchants/invoices_controller.rb, app/controllers/api/v1/merchants/items_controller.rb, config/routes.rb, spec/factories/merchants.rb, spec/models/merchant_spec.rb, spec/requests/api/v1/merchants_request_spec.rb
* Added items controller namespaced under merchants controller
* Added new namespacing routes
* Added route for invoices under merchants
* Added test to return all invoices for merchant
* Added invoices controller under merchants
=> Updates model request spec test with relationship endpoints

app/controllers/api/v1/items/invoice_items_controller.rb, app/controllers/api/v1/items/merchants_controller.rb, config/routes.rb, spec/requests/api/v1/items_request_spec.rb, spec/requests/api/v1/merchants_request_spec.rb
* Namespaced invoice_items and merchant under items
* Updated items request spec to include endpoint tests
* Added invoice_items controller under items directory
* Added merchants controller under items directory
=> Add items relationships endpoints

app/controllers/api/v1/invoice_items/invoices_controller.rb, app/controllers/api/v1/invoice_items/items_controller.rb, app/controllers/api/v1/invoices/customers_controller.rb, app/controllers/api/v1/invoices/invoice_items_controller.rb, app/controllers/api/v1/invoices/items_controller.rb, app/controllers/api/v1/invoices/merchants_controller.rb, app/controllers/api/v1/invoices/transactions_controller.rb, config/routes.rb, spec/factories/customers.rb, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/invoices_request_spec.rb
Add logic for Invoice relationship JSON outputs
* Can get invoice transactions
* Can get invoice invoice_items
* Can get invoice items
* Can get invoice customer
* Can get invoice merchant
Add logic for invoice_items relationship JSON outputs
* Can get invoice_items invoice
* Can get invoice_items item
=> Adds relationship logic for invoice and invoice_items

app/controllers/api/v1/customers/invoices_controller.rb, app/controllers/api/v1/customers/transactions_controller.rb, app/controllers/api/v1/transactions/invoices_controller.rb, app/models/customer.rb, config/routes.rb, spec/requests/api/v1/customers_request_spec.rb, spec/requests/api/v1/transactions_request_spec.rb
* Added has_many transactions to customer model
* Added routes namespacing for invoice under transactions
* Added routes namespacing for invoices and transactions under customers
* Updated customer request spec with tests
* Updated transactions request spec with tests
* Added customer directory and transactions & invoices controllers
* Added transactions directory and invoices controller
=>  Finishes transaction and customer relationship endpoints

app/controllers/api/v1/merchants/finder_controller.rb, app/controllers/api/v1/merchants/random_controller.rb, app/controllers/application_controller.rb, config/routes.rb, spec/factories/merchants.rb, spec/models/merchant_spec.rb, spec/requests/api/v1/merchants_request_spec.rb
* Add param finder to application controller
* Add sequence dates to merchants factory
* Add spec for find, find_all, and random
* Add routes and controllers for find and random in merchants namespace
@case-eee @somedayrainbows
=> Add find and random logic for merchants

app/controllers/api/v1/merchants/finder_controller.rb, app/controllers/api/v1/transactions/finder_controller.rb, app/controllers/api/v1/transactions/random_controller.rb, app/controllers/application_controller.rb, config/routes.rb, spec/factories/transactions.rb, spec/requests/api/v1/merchants_request_spec.rb, spec/requests/api/v1/transactions_request_spec.rb
* Add result and credit card number to param finder in application controller
* Add sequence dates to invoices factory
* Add spec for find, find_all, and random
* Add routes and controllers for find and random in invoices namespace
@case-eee @somedayrainbows
=> Add find and random logic for invoices

app/controllers/api/v1/invoices/finder_controller.rb, app/controllers/api/v1/invoices/random_controller.rb, app/controllers/api/v1/transactions/invoices_controller.rb, app/controllers/application_controller.rb, config/routes.rb, spec/factories/invoices.rb, spec/requests/api/v1/invoices_request_spec.rb
* Updated param_finder for invoice attributes
* Updated namespaced invoice routes for find methods
* Updated invoice factory to sequence dates
* Updated invoices request spec with finder tests
* Added finder and random controllers in invoices directory
=> Adds invoice finder methods

app/controllers/api/v1/merchants/revenue_controller.rb, app/models/merchant.rb, app/serializers/merchant_serializer.rb, app/serializers/revenue_serializer.rb, config/routes.rb, spec/factories/transactions.rb, spec/requests/api/v1/merchants_request_spec.rb
* Add in revenue instance method to Merchant model
* Add merchant revenue spec
* Add revenue serializer
=> Add Merchant Revenue

Gemfile, Gemfile.lock, app/controllers/api/v1/merchants/customers_controller.rb, app/controllers/api/v1/merchants/most_items_controller.rb, app/controllers/api/v1/merchants/revenue_controller.rb, app/models/customer.rb, app/models/merchant.rb, app/models/transaction.rb, app/serializers/customers_pending_invoices_serializer.rb, app/serializers/merchant_most_items_serializer.rb, app/serializers/revenue_serializer.rb, config/routes.rb, spec/factories/invoice_items.rb, spec/models/merchant_spec.rb, spec/requests/api/v1/merchants_request_spec.rb
Add Merchant Revenue By Date
Add Merchants With Most Items
Add Merchant customers with pending invoices
=> Add multiple BI endpoints

app/controllers/api/v1/customers/favorite_merchant_controller.rb, app/controllers/api/v1/items/best_day_controller.rb, app/models/customer.rb, app/models/item.rb, app/models/merchant.rb, config/routes.rb, spec/requests/api/v1/customers_request_spec.rb, spec/requests/api/v1/items_request_spec.rb, spec/requests/api/v1/merchants_request_spec.rb
Add item best day
Add customer favorite merchant
@case-eee @somedayrainbows
=> Add 2 Business Intelligence endpoints

app/controllers/api/v1/merchants/most_revenue_controller.rb, app/models/merchant.rb, config/routes.rb, spec/requests/api/v1/merchants_request_spec.rb
* Updated routes for most revenue
* Wrote merchant most revenue method
* Updated merchant request spec with test
* Added MostRevenueController
=> Adds merchants most revenue

app/controllers/api/v1/items/most_revenue_controller.rb, app/models/item.rb, config/routes.rb, spec/requests/api/v1/items_request_spec.rb
* Updated item routes to include most_revenue
* Added most revenue test to items request spec
* Created mostrevenuecontroller in items directory
=> Adds item_most_revenue logic

app/controllers/api/v1/items/most_items_controller.rb, app/controllers/api/v1/merchants/most_items_controller.rb, app/models/item.rb, app/serializers/merchant_most_items_serializer.rb, app/serializers/most_items_serializer.rb, config/routes.rb, spec/requests/api/v1/items_request_spec.rb
=> Add top items sold

app/controllers/api/v1/merchants/revenue_controller.rb, app/models/merchant.rb, config/routes.rb, spec/requests/api/v1/merchants_request_spec.rb
* Added self.revenue method to merchant model
* Updated routes for revenue#index
* Added test to merchant request spec
=> Adds total revenue by date all merchants

app/controllers/api/v1/merchants/favorite_customer_controller.rb, app/models/merchant.rb, config/routes.rb, spec/requests/api/v1/merchants_request_spec.rb
=> Add merchant favorite customer

app/controllers/api/v1/items/finder_controller.rb, app/controllers/api/v1/items/random_controller.rb, app/controllers/application_controller.rb, config/routes.rb, spec/factories/items.rb, spec/requests/api/v1/items_request_spec.rb
=> Add find, find_all, and random for items

app/controllers/api/v1/customers/finder_controller.rb, app/controllers/api/v1/customers/random_controller.rb, app/controllers/application_controller.rb, config/routes.rb, spec/factories/customers.rb, spec/requests/api/v1/customers_request_spec.rb
=> Customer finders

app/controllers/api/v1/invoice_items/finder_controller.rb, app/controllers/api/v1/invoice_items/random_controller.rb, app/controllers/api/v1/invoices/finder_controller.rb, app/controllers/api/v1/items/finder_controller.rb, app/controllers/api/v1/merchants/revenue_controller.rb, app/controllers/application_controller.rb, app/serializers/total_revenue_serializer.rb, config/routes.rb, spec/factories/invoice_items.rb, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/items_request_spec.rb, spec/requests/api/v1/merchants_request_spec.rb
=> Add invoice_item find, find_all, and random endpoints
